version: '3.9'

services:

  frontend:
    container_name: SRETUD-NGINX
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./setup/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - backend
    depends_on:
      - backend

  backend:
    container_name: SRETUD-PHP
    build: ./setup/backend
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database


  database:
    container_name: SRETUD-MYSQL
    build: ./setup/db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'